### ISSUE TITLE
选中某一行 左右滑动 会出现数据重叠的情况

### ISSUE THREAD

**Issue by yanhuaxuanlan** [lovebzhou/HBExcelView#1]
另外  左上角空的那块不能自定义标题？

**Comment by lovebzhou** [comment]
[_excelView registerClass:[HBExcelColumnHeader class] forReusableColumnHeaderIdentifier:@"h0"];
    [_excelView registerClass:[HBExcelColumnLabelHeader class] forReusableColumnHeaderIdentifier:@"hn"];

- (NSString *)excelView:(HBExcelView *)excelView columnHeaderIdentfierAtColumn:(NSInteger)column section:(NSInteger)section headerDatas:(NSArray *)headerDatas {
    return @"hn"; // 这样就可以自定义标题了
//    return column == 0 ? @"h0" : @"hn";
}
